# Change these first
owner: JSAnyone # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Piwigo
    url: $SERVER_BASE/piwigo/
  - name: Tandoor
    url: $SERVER_BASE/recipes/
  - name: Nextcloud
    url: $SERVER_BASE/nextcloud/
  - name: Grafana
    url: $SERVER_BASE/grafana/
  - name: Vertretungspläne
    url: $SERVER_BASE/vertretungsplaene/
  - name: Lychee
    url: $SERVER_BASE/lychee/
  - name: Google
    url: https://google.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**Uptime-Monitoring**"
  # introMessage: ""
  theme: dark
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
